### ISSUE TITLE
Images not loading in iframe when using Safari

### ISSUE THREAD

**Issue by tomwassing** [TicketVise/ticketvise#83] opened 2020-08-24 14:20 UTC
Download image from canvas URL and upload to S3.

**Comment by tomwassing** [comment] 2020-09-05 20:41
Safari seems to block the Canvas user url image since it uses cookies to retrieve the user image. Might be a good idea to combine this with #25.

**Comment by rubenjonk** [comment] 2021-02-26 08:52
Duplicate of #25

**Closed by rubenjonk** 2021-02-26 08:52 UTC
Labels: bug
